# Site settings
title: Smooth Swing
email: smoothswingapp@icloud.com
url: https://smoothswing.github.io
description: "Get distances to everything around
you - 360° - simply by pointing
your iPhone at the target."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0F059E'
  links: '#5AC8FA'

# Footer settings
footer: Smooth Swing

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com
  - title: facebook
    url: https://facebook.com
  - title: instagram
    url: http://instagram.com

# Build settings
markdown: kramdown
permalink: pretty
